Repository gear-tech/gear-js, pull requests merged in 2023-11, with the labels that each got.

#1445 Drop prepaid option in useSendMessage hook
  utils/gear-hooks/package.json
  utils/gear-hooks/src/hooks/api/useSendMessage.ts
  utils/gear-hooks/src/hooks/handlers/use-send-message-handler.ts
Labels: hooks

#1452 Refactor test-balance service
  idea/api-gateway/src/rmq.ts
  idea/common/src/jsonrpc-errors.ts
  idea/test-balance/package.json
  idea/test-balance/src/database/app-data-source.ts
  idea/test-balance/src/database/index.ts
  idea/test-balance/src/database/repositories/transfer.repository.ts
  idea/test-balance/src/database/transfer.entity.ts
  idea/test-balance/src/main.ts
  idea/test-balance/src/services/gear.ts
  idea/test-balance/src/services/index.ts
  idea/test-balance/src/services/rmq.ts
  idea/test-balance/src/services/transfer.ts
  idea/test-balance/src/transfer-balance-process.ts
  idea/test-balance/src/transfer.service.ts
  idea/test-balance/src/utils/create-account.ts
  idea/test-balance/src/utils/index.ts
  idea/test-balance/src/utils/validate-address.ts
  yarn.lock
Labels: A2-mergeoncegreen

#1455 Add modal footer and fix height with overflow
  utils/gear-ui/package-lock.json
  utils/gear-ui/package.json
  utils/gear-ui/src/components/Modal/Modal.module.scss
  utils/gear-ui/src/components/Modal/Modal.tsx
Labels: ui kit

#1456 Fix no footer modal border
  utils/gear-ui/package-lock.json
  utils/gear-ui/package.json
  utils/gear-ui/src/components/Modal/Modal.module.scss
  utils/gear-ui/src/components/Modal/Modal.tsx
Labels: ui kit

#1460 Add the ability to send message with provided pair
  utils/gear-hooks/package.json
  utils/gear-hooks/src/hooks/api/useSendMessage.ts
Labels: hooks
