Repository gear-tech/gear-js, pull requests merged in 2024-05, with the labels that each got.

#1540 Fix testnet vouchers display
  .github/workflows/CI-CD-k8s-gear-js-stage.yml
  .github/workflows/CI-CD-k8s-release-deploy.yml
  idea/frontend/.env.example
  idea/frontend/Dockerfile
  idea/frontend/src/features/voucher/hooks/use-vouchers.ts
  idea/frontend/src/features/voucher/utils.ts
  idea/frontend/src/hooks/useNetworkIcon.ts
  idea/frontend/src/shared/config/consts.ts
  idea/frontend/src/widgets/menu/model/consts.ts
Labels: frontend

#1539 fix(idea/test-balance): use transferKeepAlive method
  idea/test-balance/src/services/gear.ts
Labels: A2-mergeoncegreen

#1541 fix(idea/frontend): use `transferAllowDeath` instead of `transfer` method
  idea/frontend/src/hooks/useBalanceTransfer.ts
Labels: A2-mergeoncegreen

#1542 fix(vara-ui): input and select font-family
  utils/vara-ui/package-lock.json
  utils/vara-ui/package.json
  utils/vara-ui/src/components/input/input.module.scss
  utils/vara-ui/src/components/select/select.module.scss
Labels: ui kit

#1543 Fix payload form numeric fields submit
  idea/frontend/src/features/explorer/utils.ts
  idea/frontend/src/features/formPayload/helpers/helpers.ts
Labels: frontend

#1545 (fix/ui): ability to pass readonly `Select` options
  utils/gear-ui/package.json
  utils/gear-ui/src/components/Select/Select.tsx
  utils/vara-ui/package-lock.json
  utils/vara-ui/package.json
  utils/vara-ui/src/components/select/select.tsx
Labels: ui kit

#1546 fix(idea/frontend): hide upload wasm state button on dev node
  idea/frontend/src/pages/state/ui/wasmStates/WasmStates.tsx
Labels: frontend

#1548 chore(idea): bump `@gear-js/api` and `@polkadot/api`
  idea/common/package.json
  idea/frontend/package.json
  idea/indexer/package.json
  idea/meta-storage/package.json
  idea/test-balance/package.json
  idea/tests/package.json
  utils/gear-hooks/package.json
  yarn.lock
Labels: A2-mergeoncegreen, gear-idea

#1533 feat(idea/meta-storage): support sails idl
  .github/workflows/e2e-tests.yaml
  api/programs/rust-toolchain.toml
  idea/api-gateway/src/middleware/validate-json-rpc-request.middleware.ts
  idea/common/src/enums/api-methods.enum.ts
  idea/common/src/interfaces/api-response.ts
  idea/common/src/interfaces/rpc-request/meta-storage.ts
  idea/common/src/jsonrpc-errors.ts
  idea/meta-storage/package.json
  idea/meta-storage/src/database/data-source.ts
  idea/meta-storage/src/database/entities/code.entity.ts
  idea/meta-storage/src/database/entities/index.ts
  idea/meta-storage/src/database/entities/sails.entity.ts
  idea/meta-storage/src/rmq.ts
  idea/meta-storage/src/service.ts
  idea/meta-storage/src/util/errors.ts
  idea/tests/.gitignore
  idea/tests/e2e/meta-storage.test.ts
  idea/tests/programs/Cargo.lock
  idea/tests/programs/Cargo.toml
  idea/tests/programs/ping-sails/README.md
  idea/tests/programs/ping-sails/app/Cargo.toml
  idea/tests/programs/ping-sails/app/src/lib.rs
  idea/tests/programs/ping-sails/app/src/service.rs
  idea/tests/programs/ping-sails/wasm/.binpath
  idea/tests/programs/ping-sails/wasm/Cargo.toml
  idea/tests/programs/ping-sails/wasm/build.rs
  idea/tests/programs/ping-sails/wasm/ping.idl
  idea/tests/programs/ping-sails/wasm/src/lib.rs
Labels: A2-mergeoncegreen

#1563 fix: renovate config
  renovate.json
Labels: D4-dependencies

#1564 fix(idea/indexer): put messages in the correct order
  idea/indexer/src/services/message.service.ts
Labels: A2-mergeoncegreen

#1565 refactor(idea/backend): backend errors
  idea/api-gateway/src/main.ts
  idea/api-gateway/src/middleware/check-genesis.middleware.ts
  idea/api-gateway/src/middleware/validate-json-rpc-request.middleware.ts
  idea/api-gateway/src/server.ts
  idea/common/src/errors/base.ts
  idea/common/src/errors/code.ts
  idea/common/src/errors/index.ts
  idea/common/src/errors/jsonrpc-errors.ts
  idea/common/src/errors/message.ts
  idea/common/src/errors/meta-storage.ts
  idea/common/src/errors/program.ts
  idea/common/src/errors/signature.ts
  idea/common/src/errors/state.ts
  idea/common/src/form-response.decorator.ts
  idea/common/src/index.ts
  idea/common/src/interfaces/rpc-request/index.ts
  idea/indexer/src/common/errors/base.ts
  idea/indexer/src/common/errors/code.ts
  idea/indexer/src/common/errors/interfaces.ts
  idea/indexer/src/common/index.ts
  idea/indexer/src/services/code.service.ts
  idea/indexer/src/services/message.service.ts
  idea/indexer/src/services/program.service.ts
  idea/indexer/src/services/state.service.ts
  idea/meta-storage/src/service.ts
  idea/meta-storage/src/util/errors.ts
  idea/meta-storage/src/util/validate.ts
  idea/tests/e2e/indexer.test.ts
  idea/tests/e2e/jsonrpc-errors.test.ts
  idea/tests/e2e/meta-storage.test.ts
  idea/tests/e2e/request.ts
  idea/tests/e2e/test-balance.test.ts
Labels: A2-mergeoncegreen, D1-idea
